- name: Déployer l'application selon l'environnement
  hosts: apps
  vars:
    env_prefix: "{{ 'dev-' if env=='dev' else ('test-' if env=='test' else '') }}"
    domain_prefix: "{{ env_prefix }}"
  tasks:
    - name: Générer backend.env depuis le template
      template:
        src: templates/backend.env.j2
        dest: "{{ app_directory }}/backend.env"

    - name: Générer docker-compose.yml depuis le template
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_directory }}/docker-compose.yml"

    - name: Lancer docker-compose
      community.docker.docker_compose:
        project_src: "{{ app_directory }}"
        state: present
