name: Deploy App
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      host:
        required: true
        type: string
      app_directory:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true
      PASSWORD:
        required: true
      ADRESSE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible

      - name: Disable SSH host key checking for Ansible
        run: |
          echo "[defaults]" > ansible.cfg
          echo "host_key_checking = False" >> ansible.cfg
          cat ansible.cfg

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 62221 -H ${{ inputs.host }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 62221 student@${{ inputs.host }} "echo SSH_OK"

      - name: Create dynamic inventory
        run: |
          cat > ansible/inventory.ini << EOF[apps]
          target_host ansible_host=${{ inputs.host }} ansible_port=${{ inputs.ssh_port }} ansible_user=student ansible_become=no
          EOF

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy.yml \
            --extra-vars "env=${{ inputs.env }} \
                          image_tag=${{ github.sha }} \
                          registry=${{ secrets.ADRESSE }} \
                          registry_password=${{ secrets.PASSWORD }} \
                          app_directory=${{ inputs.app_directory }}"
