name: Deploy App
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      host:
        required: true
        type: string
      app_directory:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true
      PASSWORD:
        required: true
      ADRESSE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible

      - name: Configure SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p 62221 -H ${{ inputs.host }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Set Ansible host key checking off
        run: |
          echo "export ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -p 62221 -o StrictHostKeyChecking=no student@${{ inputs.host }} "echo SSH_OK"

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy.yml \
            --extra-vars "env=${{ inputs.env }} \
                          image_tag=${{ github.sha }} \
                          registry=${{ secrets.ADRESSE }} \
                          registry_password=${{ secrets.PASSWORD }} \
                          app_directory=${{ inputs.app_directory }}"
