name: Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:        # 👈 nécessaire pour déclencher le job sur les PR
    branches:
      - main

jobs:
  build-frontend:
    # ... ton job frontend

  build-backend:
    # ... ton job backend

  deploy-dev:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      host: dev21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland-dev
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ADRESSE: ${{ secrets.ADRESSE }}

  deploy-test:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: test
      host: test21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland-test
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ADRESSE: ${{ secrets.ADRESSE }}

  deploy-prod:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
      host: prod21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ADRESSE: ${{ secrets.ADRESSE }}

  deploy-pr:
    if: github.event_name == 'pull_request'
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: pr
      host: dev21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland-pr-${{ github.event.pull_request.number }}
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ADRESSE: ${{ secrets.ADRESSE }}
