name: Build & Push Docker Images

on:
  push:
    branches:
      - main
 
jobs:
  build-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ADRESSE }}
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/web.dockerfile
          push: true
          tags: |
            ${{ secrets.ADRESSE }}/rakotomalala-roland-frontend:latest
            ${{ secrets.ADRESSE }}/rakotomalala-roland-frontend:${{ github.sha }}

  build-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ADRESSE }}
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/api.dockerfile
          push: true
          tags: |
            ${{ secrets.ADRESSE }}/rakotomalala-roland-backend:latest
            ${{ secrets.ADRESSE }}/rakotomalala-roland-backend:${{ github.sha }}

  deploy-dev:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      host: dev21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland-dev
      ssh_key_secret: SSH_KEY

  deploy-test:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: test
      host: test21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland-test
      ssh_key_secret: SSH_KEY

  deploy-prod:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
      host: prod21.iut.arcanit.io
      app_directory: /home/student/apps/rakotomalala_roland
      ssh_key_secret: SSH_KEY